exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('foods').del()
    .then(function() {
      // Inserts seed entries
      return knex('foods').insert([{
          name: 'Apple, fuji',
          group: 'Fruit',
          calories: 69,
          fat: 0,
          sugar: 13,
          protein: 0,
          carbohydrates: 17,
          fiber: 2,
          bad_fat: 0,
        },
        {
          name: 'Apples, gala',
          group: 'Fruit',
          calories: 62,
          fat: 0,
          sugar: 11,
          protein: 0,
          carbohydrates: 15,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Apples, golden delicious',
          group: 'Fruit',
          calories: 62,
          fat: 0,
          sugar: 11,
          protein: 0,
          carbohydrates: 15,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Apple, granny smith',
          group: 'Fruit',
          calories: 63,
          fat: 0,
          sugar: 10,
          protein: 0,
          carbohydrates: 15,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Apple, red delicious',
          group: 'Fruit',
          calories: 64,
          fat: 0,
          sugar: 11,
          protein: 0,
          carbohydrates: 15,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Apricots, 1cup',
          group: 'Fruit',
          calories: 74,
          fat: 1,
          sugar: 14,
          protein: 2,
          carbohydrates: 17,
          fiber: 3,
          bad_fat: 1,
        },
        {
          name: 'Apple juice, 1cup',
          group: 'Juice',
          calories: 140,
          fat: 0,
          sugar: 23,
          protein: 0,
          carbohydrates: 35,
          fiber: 0,
          bad_fat: 0,
        },
        {
          name: 'Apple juice, organic 1cup',
          group: 'Juice',
          calories: 120,
          fat: 0,
          sugar: 24,
          protein: 0,
          carbohydrates: 30,
          fiber: 1,
          bad_fat: 0,
        },
        {
          name: 'Avocados, 100g',
          group: 'Fruit',
          calories: 160,
          fat: 15,
          sugar: 1,
          protein: 2,
          carbohydrates: 9,
          fiber: 7,
          bad_fat: 13,
        },
        {
          name: 'Avocados, 150g',
          group: 'Fruit',
          calories: 240,
          fat: 22,
          sugar: 1,
          protein: 3,
          carbohydrates: 13,
          fiber: 10,
          bad_fat: 20,
        },
        {
          name: 'Banana',
          group: 'Fruit',
          calories: 89,
          fat: 0,
          sugar: 12,
          protein: 1,
          carbohydrates: 23,
          fiber: 3,
          bad_fat: 1,
        },
        {
          name: 'Blackberries, 100g',
          group: 'Fruit',
          calories: 43,
          fat: 1,
          sugar: 5,
          protein: 1,
          carbohydrates: 10,
          fiber: 5,
          bad_fat: 0,
        },
        {
          name: 'Blackberry Juice',
          group: 'Juice',
          calories: 95,
          fat: 2,
          sugar: 19,
          protein: 1,
          carbohydrates: 20,
          fiber: 0,
          bad_fat: 1,
        },
        {
          name: 'Blueberries, 100g',
          group: 'Fruit',
          calories: 57,
          fat: 0,
          sugar: 10,
          protein: 1,
          carbohydrates: 15,
          fiber: 2,
          bad_fat: 1,
        },
        {
          name: 'Cherries, sour 155g',
          group: 'Fruit',
          calories: 78,
          fat: 1,
          sugar: 13,
          protein: 2,
          carbohydrates: 19,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Cherries, sweet 138g',
          group: 'Fruit',
          calories: 87,
          fat: 0,
          sugar: 18,
          protein: 2,
          carbohydrates: 22,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Clementines, 100g',
          group: 'Fruit',
          calories: 47,
          fat: 0,
          sugar: 9,
          protein: 1,
          carbohydrates: 12,
          fiber: 2,
          bad_fat: 0,
        },
        {
          name: 'Cranberry Juice, unsweetened 1cup',
          group: 'Juice',
          calories: 116,
          fat: 0,
          sugar: 31,
          protein: 1,
          carbohydrates: 31,
          fiber: 0,
          bad_fat: 0,
        },
        {
          name: 'Cranberries, 100g',
          group: 'Fruit',
          calories: 46,
          fat: 0,
          sugar: 4,
          protein: 1,
          carbohydrates: 12,
          fiber: 4,
          bad_fat: 0,
        },
        {
          name: 'Figs, 100g',
          group: 'Fruit',
          calories: 74,
          fat: 0,
          sugar: 16,
          protein: 1,
          carbohydrates: 19,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Goji berries, dried 28g 1 TBSP',
          group: 'Fruit',
          calories: 98,
          fat: 0,
          sugar: 13,
          protein: 4,
          carbohydrates: 22,
          fiber: 4,
          bad_fat: 0,
        },
        {
          name: 'Grapefruit Juice, 1cup',
          group: 'Juice',
          calories: 96,
          fat: 0,
          sugar: 18,
          protein: 1,
          carbohydrates: 23,
          fiber: 0,
          bad_fat: 0,
        },
        {
          name: 'Grapefruit, 100g',
          group: 'Fruit',
          calories: 32,
          fat: 0,
          sugar: 7,
          protein: 1,
          carbohydrates: 8,
          fiber: 1,
          bad_fat: 0,
        },
        {
          name: 'Grape Juice, 1cup',
          group: 'Juice',
          calories: 152,
          fat: 0,
          sugar: 36,
          protein: 1,
          carbohydrates: 38,
          fiber: 1,
          bad_fat: 0,
        },
        {
          name: 'Grapes, 100g',
          group: 'Fruit',
          calories: 69,
          fat: 0,
          sugar: 15,
          protein: 1,
          carbohydrates: 18,
          fiber: 1,
          bad_fat: 0,
        },
        {
          name: 'Guava, 100g',
          group: 'Fruit',
          calories: 68,
          fat: 1,
          sugar: 9,
          protein: 3,
          carbohydrates: 14,
          fiber: 5,
          bad_fat: 1,
        },
        {
          name: 'Kiwifruit, 100g',
          group: 'Fruit',
          calories: 61,
          fat: 1,
          sugar: 9,
          protein: 1,
          carbohydrates: 15,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Lemon, 100g',
          group: 'Fruit',
          calories: 29,
          fat: 0,
          sugar: 3,
          protein: 1,
          carbohydrates: 9,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Limes, 100g',
          group: 'Fruit',
          calories: 30,
          fat: 0,
          sugar: 2,
          protein: 1,
          carbohydrates: 11,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Mango, 100g',
          group: 'Fruit',
          calories: 60,
          fat: 2,
          sugar: 14,
          protein: 1,
          carbohydrates: 15,
          fiber: 2,
          bad_fat: 0,
        },
        {
          name: 'Cantaloupe, 100g',
          group: 'Fruit',
          calories: 34,
          fat: 0,
          sugar: 8,
          protein: 1,
          carbohydrates: 8,
          fiber: 1,
          bad_fat: 0,
        },
        {
          name: 'Honeydew, 100g',
          group: 'Fruit',
          calories: 36,
          fat: 0,
          sugar: 8,
          protein: 1,
          carbohydrates: 9,
          fiber: 1,
          bad_fat: 0,
        },
        {
          name: 'Nectarines, 100g',
          group: 'Fruit',
          calories: 44,
          fat: 0,
          sugar: 8,
          protein: 1,
          carbohydrates: 11,
          fiber: 2,
          bad_fat: 0,
        },
        {
          name: 'Olives-pickled, per olive',
          group: 'Fruit',
          calories: 4,
          fat: 1,
          sugar: 0,
          protein: 0,
          carbohydrates: 0,
          fiber: 0,
          bad_fat: 0,
        },
        {
          name: 'Orange Juice, concentrate 1cup',
          group: 'Juice',
          calories: 122,
          fat: 0,
          sugar: 21,
          protein: 2,
          carbohydrates: 29,
          fiber: 1,
          bad_fat: 0,
        },
        {
          name: 'Orange Juice, non concentrate 1cup',
          group: 'Juice',
          calories: 110,
          fat: 0,
          sugar: 23,
          protein: 2,
          carbohydrates: 26,
          fiber: 0,
          bad_fat: 0,
        },
        {
          name: 'Orange, 100g',
          group: 'Fruit',
          calories: 46,
          fat: 0,
          sugar: 9,
          protein: 1,
          carbohydrates: 12,
          fiber: 2,
          bad_fat: 0,
        },
        {
          name: 'Papaya',
          group: 'Fruit',
          calories: 43,
          fat: 0,
          sugar: 8,
          protein: 0,
          carbohydrates: 11,
          fiber: 2,
          bad_fat: 0,
        },
        {
          name: 'Passion Fruit, 100g',
          group: 'Fruit',
          calories: 60,
          fat: 0,
          sugar: 14,
          protein: 1,
          carbohydrates: 14,
          fiber: 0,
          bad_fat: 0,
        },
        {
          name: 'Peaches, 100g',
          group: 'Fruit',
          calories: 39,
          fat: 0,
          sugar: 8,
          protein: 1,
          carbohydrates: 10,
          fiber: 2,
          bad_fat: 0,
        },
        {
          name: 'Pears, 100g',
          group: 'Fruit',
          calories: 57,
          fat: 0,
          sugar: 10,
          protein: 0,
          carbohydrates: 15,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Pineapple Juice, concentrate, 1cup',
          group: 'Juice',
          calories: 132,
          fat: 0,
          sugar: 25,
          protein: 1,
          carbohydrates: 32,
          fiber: 1,
          bad_fat: 0,
        },
        {
          name: 'Pineapple Juice, unsweetened, 1cup',
          group: 'Juice',
          calories: 125,
          fat: 0,
          sugar: 25,
          protein: 1,
          carbohydrates: 31,
          fiber: 1,
          bad_fat: 0,
        },
        {
          name: 'Pineapple, 100g',
          group: 'Fruit',
          calories: 50,
          fat: 0,
          sugar: 10,
          protein: 1,
          carbohydrates: 13,
          fiber: 1,
          bad_fat: 0,
        },
        {
          name: 'Plums, 100g',
          group: 'Fruit',
          calories: 46,
          fat: 0,
          sugar: 10,
          protein: 1,
          carbohydrates: 11,
          fiber: 1,
          bad_fat: 0,
        },
        {
          name: 'Pomegranate juice, 1cup',
          group: 'Juice',
          calories: 134,
          fat: 1,
          sugar: 32,
          protein: 0,
          carbohydrates: 33,
          fiber: 0,
          bad_fat: 0,
        },
        {
          name: 'Pomegranate, 100g',
          group: 'Fruit',
          calories: 83,
          fat: 1,
          sugar: 14,
          protein: 2,
          carbohydrates: 19,
          fiber: 4,
          bad_fat: 0,
        },
        {
          name: 'Raisins, 100g',
          group: 'Fruit',
          calories: 299,
          fat: 0,
          sugar: 59,
          protein: 3,
          carbohydrates: 79,
          fiber: 4,
          bad_fat: 0,
        },
        {
          name: 'Raspberries, 100g',
          group: 'Fruit',
          calories: 52,
          fat: 1,
          sugar: 4,
          protein: 1,
          carbohydrates: 12,
          fiber: 7,
          bad_fat: 0,
        },
        {
          name: 'Strawberries, 100g',
          group: 'Fruit',
          calories: 32,
          fat: 0,
          sugar: 5,
          protein: 1,
          carbohydrates: 8,
          fiber: 2,
          bad_fat: 0,
        },
        {
          name: 'Tangerine, 100g',
          group: 'Fruit',
          calories: 53,
          fat: 0,
          sugar: 11,
          protein: 1,
          carbohydrates: 13,
          fiber: 2,
          bad_fat: 0,
        },
        {
          name: 'Watermelon, 100g',
          group: 'Fruit',
          calories: 30,
          fat: 0,
          sugar: 6,
          protein: 1,
          carbohydrates: 7,
          fiber: 0,
          bad_fat: 0,
        },
        {
          name: 'Arugula, 100g',
          group: 'Vegetable',
          calories: 25,
          fat: 1,
          sugar: 2,
          protein: 3,
          carbohydrates: 4,
          fiber: 2,
          bad_fat: 0,
        },
        {
          name: 'Artichoke, 100g',
          group: 'Vegetable',
          calories: 47,
          fat: 0,
          sugar: 1,
          protein: 3,
          carbohydrates: 11,
          fiber: 5,
          bad_fat: 0,
        },
        {
          name: 'Asparagus, 100g',
          group: 'Vegetable',
          calories: 20,
          fat: 0,
          sugar: 2,
          protein: 2,
          carbohydrates: 4,
          fiber: 2,
          bad_fat: 0,
        },
        {
          name: 'Beets, 100g',
          group: 'Vegetable',
          calories: 43,
          fat: 0,
          sugar: 7,
          protein: 2,
          carbohydrates: 10,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Broccoli, 100g',
          group: 'Vegetable',
          calories: 34,
          fat: 0,
          sugar: 2,
          protein: 3,
          carbohydrates: 7,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Brussel Sprouts, 100g',
          group: 'Vegetable',
          calories: 43,
          fat: 0,
          sugar: 2,
          protein: 3,
          carbohydrates: 9,
          fiber: 4,
          bad_fat: 0,
        },
        {
          name: 'Cabbage, 100g',
          group: 'Vegetable',
          calories: 25,
          fat: 0,
          sugar: 3,
          protein: 1,
          carbohydrates: 6,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Carrots, 100g',
          group: 'Vegetable',
          calories: 41,
          fat: 0,
          sugar: 5,
          protein: 1,
          carbohydrates: 10,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Cauliflower, 100g',
          group: 'Vegetable',
          calories: 25,
          fat: 0,
          sugar: 2,
          protein: 2,
          carbohydrates: 5,
          fiber: 2,
          bad_fat: 0,
        },
      ]);
    });
};
