exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('foods').del()
    .then(function() {
      // Inserts seed entries
      return knex('foods').insert([{
          name: 'Apple, fuji',
          group: 'Fruit',
          calories: 69,
          fat: 0,
          sugar: 13,
          protein: 0,
          carbohydrates: 17,
          fiber: 2,
          bad_fat: 0,
        },
        {
          name: 'Apples, gala',
          group: 'Fruit',
          calories: 62,
          fat: 0,
          sugar: 11,
          protein: 0,
          carbohydrates: 15,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Apples, golden delicious',
          group: 'Fruit',
          calories: 62,
          fat: 0,
          sugar: 11,
          protein: 0,
          carbohydrates: 15,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Apple, granny smith',
          group: 'Fruit',
          calories: 63,
          fat: 0,
          sugar: 10,
          protein: 0,
          carbohydrates: 15,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Apple, red delicious',
          group: 'Fruit',
          calories: 64,
          fat: 0,
          sugar: 11,
          protein: 0,
          carbohydrates: 15,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Apricots, 1cup',
          group: 'Fruit',
          calories: 74,
          fat: 1,
          sugar: 14,
          protein: 2,
          carbohydrates: 17,
          fiber: 3,
          bad_fat: 1,
        },
        {
          name: 'Apple juice, 1cup',
          group: 'Juice',
          calories: 140,
          fat: 0,
          sugar: 23,
          protein: 0,
          carbohydrates: 35,
          fiber: 0,
          bad_fat: 0,
        },
        {
          name: 'Apple juice, organic 1cup',
          group: 'Juice',
          calories: 120,
          fat: 0,
          sugar: 24,
          protein: 0,
          carbohydrates: 30,
          fiber: 1,
          bad_fat: 0,
        },
        {
          name: 'Avocados, 100g',
          group: 'Fruit',
          calories: 160,
          fat: 15,
          sugar: 1,
          protein: 2,
          carbohydrates: 9,
          fiber: 7,
          bad_fat: 13,
        },
        {
          name: 'Avocados, 150g',
          group: 'Fruit',
          calories: 240,
          fat: 22,
          sugar: 1,
          protein: 3,
          carbohydrates: 13,
          fiber: 10,
          bad_fat: 20,
        },
        {
          name: 'Banana',
          group: 'Fruit',
          calories: 89,
          fat: 0,
          sugar: 12,
          protein: 1,
          carbohydrates: 23,
          fiber: 3,
          bad_fat: 1,
        },
        {
          name: 'Blackberries, 100g',
          group: 'Fruit',
          calories: 43,
          fat: 1,
          sugar: 5,
          protein: 1,
          carbohydrates: 10,
          fiber: 5,
          bad_fat: 0,
        },
        {
          name: 'Blackberry Juice',
          group: 'Juice',
          calories: 95,
          fat: 2,
          sugar: 19,
          protein: 1,
          carbohydrates: 20,
          fiber: 0,
          bad_fat: 1,
        },
        {
          name: 'Blueberries, 100g',
          group: 'Fruit',
          calories: 57,
          fat: 0,
          sugar: 10,
          protein: 1,
          carbohydrates: 15,
          fiber: 2,
          bad_fat: 1,
        },
        {
          name: 'Cherries, sour 155g',
          group: 'Fruit',
          calories: 78,
          fat: 1,
          sugar: 13,
          protein: 2,
          carbohydrates: 19,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Cherries, sweet 138g',
          group: 'Fruit',
          calories: 87,
          fat: 0,
          sugar: 18,
          protein: 2,
          carbohydrates: 22,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Clementines, 100g',
          group: 'Fruit',
          calories: 47,
          fat: 0,
          sugar: 9,
          protein: 1,
          carbohydrates: 12,
          fiber: 2,
          bad_fat: 0,
        },
        {
          name: 'Cranberry Juice, unsweetened 1cup',
          group: 'Juice',
          calories: 116,
          fat: 0,
          sugar: 31,
          protein: 1,
          carbohydrates: 31,
          fiber: 0,
          bad_fat: 0,
        },
        {
          name: 'Cranberries, 100g',
          group: 'Fruit',
          calories: 46,
          fat: 0,
          sugar: 4,
          protein: 1,
          carbohydrates: 12,
          fiber: 4,
          bad_fat: 0,
        },
        {
          name: 'Figs, 100g',
          group: 'Fruit',
          calories: 74,
          fat: 0,
          sugar: 16,
          protein: 1,
          carbohydrates: 19,
          fiber: 3,
          bad_fat: 0,
        },
        {
          name: 'Goji berries, dried 28g 1 TBSP',
          group: 'Fruit',
          calories: 98,
          fat: 0,
          sugar: 13,
          protein: 4,
          carbohydrates: 22,
          fiber: 4,
          bad_fat: 0,
        },
        {
          name: 'Grapefruit Juice, 1cup',
          group: 'Juice',
          calories: 96,
          fat: 0,
          sugar: 18,
          protein: 1,
          carbohydrates: 23,
          fiber: 0,
          bad_fat: 0,
        },
        {
          name: 'Grapefruit, 100g',
          group: 'Fruit',
          calories: 32,
          fat: 0,
          sugar: 7,
          protein: 1,
          carbohydrates: 8,
          fiber: 1,
          bad_fat: 0,
        },
      ]);
    });
};
